name: flutter_whisper_kit
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  pigeon: ^26.0.1


flutter:
  plugin:
    platforms:
      android:
        package: com.hoicham.flutter_whisper_kit
        pluginClass: FlutterWhisperKitPlugin
      ios:
        pluginClass: FlutterWhisperKitPlugin